Tuple type
scylladb-zpp-2024-javascript-driver/scylladb-javascript-driver pull request #101
Opened 2024-11-18 20:47 UTC by PiotrJunior

2025-03-03 08:16 UTC, adespawn requested changes
I'm not fully convinced by the approach used to store the type. At lest the approach of having nested type should be explained somewhere. 

I also believe there are some integration tests that can be enabled with working tuple type

2025-03-03 08:16 UTC, adespawn commented on lib/types/tuple.js
> +        this.#internal = rust.TupleWrapper.new();
Wouldn't it be better to store ``isJsStored`` as a local variable, and if it's JsStored, then have null instead of empty ``#internal``?

2025-03-03 08:16 UTC, adespawn commented on src/types/tuple.rs
> +    values: Option<Vec<Option<CqlValue>>>,
What is motivation behind second Option?

2025-03-03 08:16 UTC, adespawn commented on lib/types/tuple.js
> +    }
Question for later, when we have benchmarks:
Maybe it's better to store a value in JS when it's converted the first time?

2025-03-03 08:26 UTC, Stapox35 requested changes

2025-03-03 08:26 UTC, Stapox35 commented on lib/types/tuple.js
> + * As tuples can be used as a Map keys, the {@link Tuple#toString toString()} method calls toString of each element,
This hyperlink not working in docs.

2025-03-03 08:26 UTC, Stapox35 commented on lib/types/tuple.js
> +        // This is Rust driver limitation
```suggestion
        // This is Rust driver limitation.
```

2025-03-03 08:26 UTC, Stapox35 commented on lib/types/tuple.js
> +     * Creates a new instance of a tuple based on the Array
```suggestion
     * Creates a new instance of a tuple based on the Array.
```

2025-03-03 08:26 UTC, Stapox35 commented on lib/types/tuple.js
> +        // Apply the elements Array as parameters
```suggestion
        // Apply the elements Array as parameters.
```

2025-03-03 08:26 UTC, Stapox35 commented on lib/types/tuple.js
> +     * Gets the elements as an array
```suggestion
     * Gets the elements as an array.
```

2025-03-03 08:26 UTC, Stapox35 commented on lib/types/tuple.js
> +     * Get tuple from rust object. Not intended to be exposed in the API
```suggestion
     * Get tuple from rust object. Not intended to be exposed in the API.
```

2025-03-03 08:26 UTC, Stapox35 commented on lib/types/tuple.js
> +
In Datastax I can't call fromArray([]) (throw error), but in yours implementation I can call fromArray([]). Why did you change driver behaviour?

2025-03-03 08:50 UTC, PiotrJunior commented on src/tests/request_values_tests.rs
> +    }
match in this file requires (ComplexType, SimpleType, SimpleType), but in order for Tuple tests to work I need (ComplexType, ComplexType, ComplexType)

2025-03-03 08:52 UTC, PiotrJunior commented on test/unit/tuple-tests.js
Tuple is read only type and cannot be empty

2025-03-03 13:10 UTC, PiotrJunior commented on lib/types/tuple.js
> + * As tuples can be used as a Map keys, the {@link Tuple#toString toString()} method calls toString of each element,
Currenty undebugable as JSdoc don't work

2025-03-03 13:12 UTC, PiotrJunior commented on lib/types/tuple.js
> +    }
remember that, that solution will bemore memory expensive

2025-03-03 13:53 UTC, PiotrJunior commented on src/types/tuple.rs
> +    values: Option<Vec<Option<CqlValue>>>,
Tuple can contain null values
Chceck CqlType::Tuple

2025-03-03 14:47 UTC, wprzytula commented on lib/types/tuple.js
> + * As tuples can be used as a Map keys, the {@link Tuple#toString toString()} method calls toString of each element,
>  JSdoc don't work
WDYM? Why? Shouldn't someone _volunteer_ to investigate it?
I'm sooo happy that you've agreed to volunteer @PiotrJunior !!!

2025-03-03 16:53 UTC, adespawn commented on lib/types/tuple.js
> + * As tuples can be used as a Map keys, the {@link Tuple#toString toString()} method calls toString of each element,
It would be nice to see CI no longer failing on main 😉

2025-03-07 12:07 UTC, wprzytula requested changes

2025-03-07 12:07 UTC, wprzytula commented on src/tests/request_values_tests.rs
> +    }
:recycle: Can we make it another case of the `match` below? We can use `return` in its branch, so that we don't have to conform to other branches wrt return type.

2025-03-11 09:51 UTC, PiotrJunior commented on src/result.rs
> +    }
If I would switch this error type and message, it would be inconsistent with other thrown errors in this file

2025-03-11 17:05 UTC, wprzytula commented on src/result.rs
> +    }
Then my message applies to errors thrown in the whole file. If something's broken, you are not supposed to install more broken parts in it.

2025-03-25 11:51 UTC, adespawn commented on src/types/type_wrappers.rs
> +    }
Is the recursive format the best way to store this information?

2025-03-25 14:05 UTC, PiotrJunior commented on lib/types/tuple.js
> + * Tuples are sequences, just like Arrays. The only difference is that tuples can't be changed.
I'm comparing to JS Arrays, and yes they can store multiple diffrent types

2025-03-25 18:49 UTC, wprzytula requested changes

2025-03-25 18:49 UTC, wprzytula commented on src/result.rs
> +    }
Bump

2025-03-25 18:49 UTC, wprzytula commented on src/types/type_wrappers.rs
> +    }
Oh Ferris... what have those hellish (GC? too much FP? can't even say who is the largest culprit...) languages done to our poor Piotr...

2025-03-25 18:49 UTC, wprzytula commented on lib/types/cql-utils.js
> + * @param {rust.ComplexType} complexType
ditto: this is not the most informative name.

2025-03-25 18:49 UTC, wprzytula commented on lib/types/cql-utils.js
> +    }
Please, don't. Don't implement tuple as a linked list... Ferris is already crying. I need to calm him down all the time.

2025-03-25 18:49 UTC, wprzytula commented on src/tests/request_values_tests.rs
> +        }
I have absolutely never seen a tuple represented as a tree. @PiotrJunior, you have unique talent of bringing up very extraordinary solutions.

2025-04-08 09:11 UTC, PiotrJunior commented on lib/types/tuple.js
> + * Tuples are sequences, just like Arrays. The only difference is that tuples can't be changed.
link was removed as it was refering JS Arrays what cannot be linked in JSDoc afaik

2025-04-15 08:29 UTC, adespawn requested changes

2025-04-15 08:29 UTC, adespawn commented on src/types/tuple.rs
> +    }
Do we need to allow empty tuples, if we can have null instead of tuple with None elements?

2025-04-15 08:29 UTC, adespawn commented on test/unit/cql-value-wrapper-tests.js
Js part of this test is missing.

2025-04-15 08:29 UTC, adespawn commented on examples/DataStax/tuple/tuple-insert-select-simple.js
> +        );
1. Why this syntax.
2. You provide only two values for three %s?

2025-04-15 08:29 UTC, adespawn commented on examples/DataStax/tuple/tuple-insert-select-simple.js
> +        console.log("Inserting");
Is this nesesery?

2025-04-15 08:29 UTC, adespawn commented on test/unit/cql-value-wrapper-tests.js
Correction: it's in the wrong commit

2025-04-15 08:29 UTC, adespawn commented on test/unit/cql-value-wrapper-tests.js
> -        assert.strictEqual(value.get(2), null);
Why are you changing this? Does the behavior of the tuple changed?

2025-04-15 08:29 UTC, adespawn commented on lib/types/tuple.js
Why split performance improvements into a different commit if it's a part of a single PR?
Implement them from the beginning.

2025-04-15 08:37 UTC, PiotrJunior commented on examples/DataStax/tuple/tuple-insert-select-simple.js
> +        );
This test is narrowed version of other test with Tuples but with Varint type removed. I missed this spot when removing Varint.

2025-04-15 08:40 UTC, adespawn commented on examples/DataStax/tuple/tuple-insert-select-simple.js
> +        );
So just update it, ~~in case temporary solution becomes a permanent~~

2025-04-15 08:42 UTC, adespawn commented on test/unit/cql-value-wrapper-tests.js
> -        assert.strictEqual(value.get(2), null);
So why it was different initially?

2025-04-15 09:57 UTC, PiotrJunior commented on test/unit/cql-value-wrapper-tests.js
> -        assert.strictEqual(value.get(2), null);
I didn't saw it this test in integration tests at first

2025-04-15 09:59 UTC, PiotrJunior commented on lib/types/tuple.js
1 additional commit was easier than editing 3 different commits

2025-04-15 10:20 UTC, adespawn commented on src/result.rs
> +    }
@PiotrJunior

2025-04-15 10:40 UTC, PiotrJunior commented on lib/types/tuple.js
> +        return resultWrapper.getCqlObject(this.#internal.get(index || 0));
Similar functionality was implemented by DataStax and DataStax also marked its type as Number: https://docs.datastax.com/en/drivers/nodejs-dse/1.0/module-types-Tuple.html#get
This ensures more readable documentation for users and also don't break backwards compatibility

2025-04-15 10:54 UTC, PiotrJunior commented on src/result.rs
> +    }
I added issue [#185](https://github.com/scylladb-zpp-2024-javascript-driver/scylladb-javascript-driver/issues/185) for it

2025-04-16 08:19 UTC, wprzytula commented
Please resolve conflicts and then request my review.

2025-04-27 14:05 UTC, adespawn requested changes

2025-04-27 14:05 UTC, adespawn commented on test/unit/cql-value-wrapper-tests.js
Still not fixed

2025-04-27 14:05 UTC, adespawn commented on test/unit-not-supported/basic-tests.js
If this commit only enables tests, name it accordingly

2025-04-27 14:05 UTC, adespawn commented on src/tests/request_values_tests.rs
While is not strictly tuple related, it would be nice to see double some nested types

2025-04-27 14:05 UTC, adespawn commented on examples/DataStax/tuple/tuple-insert-select-simple.js
https://github.com/scylladb-zpp-2024-javascript-driver/scylladb-javascript-driver/pull/172#discussion_r2033271239

I think the same applies here

2025-04-28 09:06 UTC, wprzytula requested changes

2025-04-28 09:17 UTC, adespawn commented on lib/types/tuple.js
>  }
Formally this function is exposed, but is almost invisible to user thaks to  ``@package`` tag (which btw, should be last).

In other words, user can call it, but documentation (including in code editor) will not suggest or recognize this function
https://jsdoc.app/tags-package

2025-04-28 09:23 UTC, adespawn commented on src/types/type_wrappers.rs
> +    pub(crate) inner_types: Vec<ComplexType>, // Used by Tuple and UDT
When it's privet (or package pub) then this is not a problem. It's only the case when the value is pub

2025-04-28 10:10 UTC, adespawn commented on lib/types/tuple.js
>  }
Yes

2025-04-29 09:23 UTC, adespawn requested changes

2025-04-29 09:23 UTC, adespawn commented on examples/other/tuple-insert-select-simple.js
> +        );
```suggestion
        console.log(
            `${row["currencies"].get(0)} to ${row["currencies"].get(1)}`,
        );
```

2025-04-29 09:23 UTC, adespawn commented on lib/types/cql-utils.js
> +        const element = value.get(i) !== undefined ? value.get(i) : null;
So to confirm: tuple can have null values?

2025-04-29 09:23 UTC, adespawn commented on lib/types/tuple.js
> + * Tuples are sequences, just like Arrays. The only difference is that tuples can't be changed.
```suggestion
 * Tuples are sequences, just like Arrays. The only difference is that tuples are read only.
```

2025-04-29 09:23 UTC, adespawn commented on lib/types/tuple.js
> +     * @returns {Tuple}
```suggestion
     * @param {Array<resultWrapper.CqlValueWrapper | null>} rustTuple
     * @returns {Tuple}
     * @package
```

2025-04-29 09:23 UTC, adespawn commented on lib/types/tuple.js
> +            e == null ? undefined : resultWrapper.getCqlObject(e),
```suggestion
            e === null ? undefined : resultWrapper.getCqlObject(e),
```

2025-04-29 09:23 UTC, adespawn commented on src/requests/parameter_wrappers.rs
> +                val.iter().map(|f| f.map(|f| f.parameter.clone())).collect(),
You shadow f with other f

2025-04-29 09:23 UTC, adespawn commented on src/result.rs
> +                .map(|v| v.as_ref().map(|v| CqlValueWrapper { inner: v.clone() }))
you shadow v with other v

2025-04-29 09:23 UTC, adespawn commented on src/types/type_wrappers.rs
> +    pub(crate) inner_types: Vec<ComplexType>, // Used by Tuple and UDT
bump

2025-04-29 10:21 UTC, ZuzaOsa requested changes

2025-04-29 10:21 UTC, ZuzaOsa commented on lib/types/tuple.js
> + * to try to get a unique string key.
```suggestion
 * trying to get a unique string key.
```

2025-04-29 10:21 UTC, ZuzaOsa commented on lib/types/tuple.js
> +     * Returns the elements of the tuple.
```suggestion
     * Returns elements of the tuple.
```

2025-04-29 10:21 UTC, ZuzaOsa commented on lib/types/tuple.js
> +     * Creates a new instance of a tuple based on the Array.
Here you have `instance of a tuple` and before there is `instance of Tuple`. Please make those consistent.

2025-04-29 10:21 UTC, ZuzaOsa commented on lib/types/tuple.js
> +        // Apply the elements Array as parameters.
Shouldn't this comment be something like `Create a Tuple from an Array`?

2025-04-29 10:21 UTC, ZuzaOsa commented on lib/types/tuple.js
> +     * Returns the value located at the index.
```suggestion
     * Returns value located at the given index.
```

2025-04-29 10:21 UTC, ZuzaOsa commented on lib/types/tuple.js
> +     * Returns the string representation of the sequence surrounded by parenthesis, ie: (1, 2).
```suggestion
     * Returns a string representation of the sequence, surrounded by parenthesis, ie: (1, 2).
```

2025-04-29 10:21 UTC, ZuzaOsa commented on lib/types/tuple.js
> +     * Returns the Array representation of the sequence.
```suggestion
     * Returns an Array representation of the sequence.
```

2025-04-29 10:21 UTC, ZuzaOsa commented on lib/types/tuple.js
> +     * Gets the elements as an array.
```suggestion
     * Gets the elements as an Array.
```

2025-04-29 10:47 UTC, PiotrJunior commented on lib/types/cql-utils.js
> +        const element = value.get(i) !== undefined ? value.get(i) : null;
yes

2025-04-29 11:02 UTC, PiotrJunior commented on examples/DataStax/tuple/tuple-insert-select.js.broekn
> +            "{'class': 'NetworkTopologyStrategy', 'replication_factor': '1' }";
This test require Varint which isn't supported for now

2025-04-29 11:03 UTC, ZuzaOsa requested changes

2025-04-29 11:03 UTC, ZuzaOsa commented on lib/types/tuple.js
> +        // Apply the elements Array as parameters.
```suggestion
        // Use the elements of an Array as function parameters.
```

2025-04-29 11:16 UTC, adespawn approved these changes

2025-04-29 12:06 UTC, wprzytula approved these changes

2025-04-29 12:06 UTC, wprzytula commented
The filename is still `broekn`, not `broken`.

2025-04-29 15:21 UTC, ZuzaOsa approved these changes

2025-04-30 08:46 UTC, wprzytula commented
Can we merge this?

2025-04-30 09:20 UTC, adespawn commented
> The filename is still `broekn`, not `broken`.

Depends if you want to wait for this fix

2025-04-30 09:31 UTC, merged