Add support for client options
scylladb-zpp-2024-javascript-driver/scylladb-javascript-driver pull request #110
Opened 2024-11-24 10:53 UTC by ZuzaOsa

2025-02-20 07:33 UTC, adespawn requested changes
If I understand correctly, the authentication part will work correctly if username and password will be provided, but not if the PlainTextAuthProvider as authProvider option

2025-02-20 07:33 UTC, adespawn commented on lib/client.js
>          this.rustOptions = rustOptions;
If you moved code related to client options to separate function, maybe move it also in JS?

2025-03-18 10:38 UTC, adespawn commented
Did you checked if any integration tests can be enabled with those changes?

2025-03-19 07:52 UTC, wprzytula requested changes

2025-03-19 07:52 UTC, wprzytula commented on lib/client-options.js
>   * @property {String} [keyspace] The logged keyspace for all the connections created within the {@link Client} instance.
:wrench: This TODO is obsolete in this commit.

2025-03-19 07:52 UTC, wprzytula commented on src/session.rs
> +        Ok(SessionWrapper { inner: session })
:wrench: There is a `use_keyspace()` method on `SessionBuilder` that should be used instead of `use`ing the keyspace on an already set up `Session`.

2025-03-19 07:52 UTC, wprzytula commented on src/session.rs
> +    builder = builder.custom_identity(get_self_identity(options));
:pick: It really pains me when I see naming of `get_*` when not really referring to just retrieving a field. We should rather use `create_*`, `build_*`, `configure_*` etc., whichever you find best.

2025-03-19 07:52 UTC, wprzytula commented on src/session.rs
> +    builder = builder.custom_identity(get_self_identity(options));
The same goes for `getWrappedType`. IMO, it should be `wrapType`, because the wrapped type has not existed anywhere yet -- we are creating it on-fly.

2025-03-19 07:52 UTC, wprzytula commented on lib/client-options.js
>   * auth-enabled cluster, but not both.
:pick: typo in commit message: `suport` -> `support`

2025-03-19 07:52 UTC, wprzytula commented on src/session.rs
> +    }
Here we skip setting credentials **silently** if some credential is missing - this is unacceptable.

2025-03-19 07:52 UTC, wprzytula commented on lib/client-options.js
>   * generate a random identifier.
:wrench: You removed TODO for `id`, but I don't see where it's supported.

2025-03-19 07:52 UTC, wprzytula commented on lib/auth/plain-text-auth-provider.js
>  util.inherits(PlainTextAuthProvider, AuthProvider);
:question: Shouldn't this also be converted to the classes syntax, i.e., `extends`?

2025-03-19 07:52 UTC, wprzytula commented on lib/auth/plain-text-auth-provider.js
>  util.inherits(PlainTextAuthenticator, Authenticator);
ditto

2025-03-19 08:10 UTC, ZuzaOsa commented on lib/client-options.js
>   * @property {String} [keyspace] The logged keyspace for all the connections created within the {@link Client} instance.
The TODOs are after the description not before. This was discussed with @adespawn when reviewing #78 and is done this way because it displays better in the compiled docs.

2025-03-19 15:34 UTC, wprzytula commented on lib/client-options.js
>   * @property {String} [keyspace] The logged keyspace for all the connections created within the {@link Client} instance.
Oh, OK.

2025-03-20 08:41 UTC, ZuzaOsa commented on src/session.rs
> +    }
DataStax driver throws an error if partial credentials are provided, the check is performed in the `extend` function in `client-options.js` (using `validateAuthenticationOptions` function).

2025-03-20 09:39 UTC, wprzytula commented on src/session.rs
> +    }
> DataStax driver throws an error if partial credentials are provided, the check is performed in the `extend` function in `client-options.js` (using `validateAuthenticationOptions` function).

Does this imply that with present code:
1. we would have already thrown an error if we were to call this code with partial credentials, or
2. we need to introduce the check?

2025-03-20 11:27 UTC, ZuzaOsa commented on src/session.rs
> +    }
We would throw an error while executing the client constructor.

2025-03-25 07:05 UTC, wprzytula requested changes

2025-03-25 07:05 UTC, wprzytula commented on src/session.rs
> +    }
Then, let's throw `unreachable!()` upon error here instead of silent ignore.
```suggestion
    match (
        options.credentials_username.as_ref(),
        options.credentials_password.as_ref(),
    ) {
        (Some(username), Some(password)) => {
            builder = builder.user(username, password);
        }
        (None, None) => (),
        (Some(_), None) | (None, Some(_)) => {
            unreachable!("There is a check in JS Client constructor that should have prevented only one credential passed")
        }
    }
```

2025-03-25 07:05 UTC, wprzytula commented on src/session.rs
> +    }
:thought_balloon: Even better: we could change credentials' representation in `ClientOptions` from (`Option<String>, Option<String>)` into `Option<(String, String)>`. Or couldn't we?

2025-04-07 13:26 UTC, ZuzaOsa commented on src/session.rs
> +    }
It is a tuple so passing it was not yet introduced in the napi version we are using.

2025-04-07 14:59 UTC, adespawn requested changes

2025-04-07 14:59 UTC, adespawn commented on lib/auth/plain-text-auth-provider.js
>   * @constructor
classdesc and constructor tags no longer needed.

Move description of constructor to constructor

2025-04-07 14:59 UTC, adespawn commented on lib/client.js
> +
If we have ``client-options.js``, then maybe it would be a better place for this function?

2025-04-08 06:10 UTC, ZuzaOsa commented on lib/client.js
> +
Then we would export a private function, I don't know if it is better.

2025-04-08 06:57 UTC, adespawn commented on lib/client.js
> +
From client options file only default options are exported by the driver:
https://github.com/scylladb-zpp-2024-javascript-driver/scylladb-javascript-driver/blob/b3037b3ab0f6256b27ec1db7aa6a2d83b9befdcc/main.js#L14
https://github.com/scylladb-zpp-2024-javascript-driver/scylladb-javascript-driver/blob/b3037b3ab0f6256b27ec1db7aa6a2d83b9befdcc/main.js#L42-L44

2025-04-08 11:30 UTC, adespawn approved these changes
LGTM

2025-04-08 12:42 UTC, wprzytula approved these changes

2025-04-08 12:51 UTC, merged