Fisrts iteration of new driver
scylladb-zpp-2024-javascript-driver/scylladb-javascript-driver pull request #56
Opened 2024-10-31 12:58 UTC by adespawn

***REMEMBER TO EDIT THIS MESSAGE, WHEN MERGING TO THIS BRANCH***

Things already merged into this branch:

Things required to finish this branch:

- [ ] Add implementation for CQL types (feature branch: ``types-support``)
- [ ] Add implementation for connecting to database (Currently very basic implementation in this branch)
- [ ] Add ability to executing queries with parameters (WIP on ``branch execute-parameters``)

Issues related to this PR:
#10, #12, #13, #14, #15, #28

Things to consider adding in this PR:

(Feel free to edit / add new requirements)

2024-12-18 10:58 UTC, PiotrJunior requested changes
Move Rust test files to test directory.
Fix filenames in JS tests (*-tests and .js.js).
Enable typescript tests.

2024-12-18 10:58 UTC, PiotrJunior commented on lib/client.js
> +    shutdown(callback) {
Mark as deprecated

2024-12-18 10:58 UTC, PiotrJunior commented on lib/client.js
> +    getState() {
Look further into this

2024-12-18 10:58 UTC, PiotrJunior commented on lib/client.js
> +    async handleSchemaAgreementAndRefresh(connection, event) {
Does this work in our driver and do we need this to be public?

2024-12-18 10:58 UTC, PiotrJunior commented on src/types/local_time.rs
> +                "".to_string()
Fix this

2024-12-18 10:58 UTC, PiotrJunior commented on src/lib.rs
Remove test_connection above

2024-12-18 10:58 UTC, PiotrJunior commented on test/unit/inet-address-tests.js
> +        // TODO: DataStax throws TypeErrors, but due to napi-rs limitations, we temporarily throw Errors.
DO

2024-12-18 10:58 UTC, PiotrJunior commented on eslint.config.mjs
> +      // TODO: FIX
DO: FIX

2024-12-18 11:57 UTC, PiotrJunior requested changes
- Move test files from rust directory to test directory.
- Make sure typescript tests works.
- Something more but I dont remember what

2025-01-15 09:50 UTC, adespawn commented on eslint.config.mjs
> +      // TODO: FIX
Otwarty PR

2025-01-15 09:51 UTC, adespawn commented on lib/client.js
> +    shutdown(callback) {
Otwarty PR

2025-01-15 09:54 UTC, adespawn commented on lib/client.js
> +    getState() {
Otwarty PR

2025-01-22 09:51 UTC, wprzytula approved these changes

2025-01-22 09:53 UTC, Stapox35 approved these changes

2025-01-22 09:53 UTC, PiotrJunior approved these changes

2025-01-22 09:55 UTC, merged