Cql value wrapper refactor
scylladb-zpp-2024-javascript-driver/scylladb-javascript-driver pull request #59
Opened 2024-11-02 12:14 UTC by adespawn

2024-11-03 09:42 UTC, adespawn commented
In the last commit I added some unit tests for the layer between rust and node js. Before I add them for other types, pleas let me know if the current approach looks good. 

@wprzytula

2024-11-04 16:30 UTC, PiotrJunior commented
Why in 'result.rs' there is:
```rust

#[napi]
impl QueryResultWrapper {
    pub fn from_query(_internal: QueryResult) -> QueryResultWrapper {
        let x = _internal;
        QueryResultWrapper { internal: x }
    }
```
instead of 
```rust

#[napi]
impl QueryResultWrapper {
    pub fn from_query(internal: QueryResult) -> QueryResultWrapper {
        QueryResultWrapper { internal }
    }
```

2024-11-04 18:59 UTC, adespawn commented
> Why in 'result.rs' there is:
> 
> ```rust
> #[napi]
> impl QueryResultWrapper {
>     pub fn from_query(_internal: QueryResult) -> QueryResultWrapper {
>         let x = _internal;
>         QueryResultWrapper { internal: x }
>     }
> ```

No clue, fixed that.

2024-11-05 07:31 UTC, wprzytula commented on src/result.rs
>  }
Naming nit: it's customary in Rust to write `inner` instead of `internal` in case of wrappers.

2024-11-05 12:09 UTC, ZuzaOsa requested changes

2024-11-05 12:09 UTC, ZuzaOsa commented on lib/types/results-wrapper.js
> + * @param {rust.CqlValueWrapper} field
`Checks` instead `Check`

2024-11-05 12:09 UTC, ZuzaOsa commented on lib/types/results-wrapper.js
> + * @returns {Array<Row> | undefined} Returns array of rows if ResultWrapper has some, and undefined if has None
`if ResultWrapper has any, and undefined otherwise` would sound better imo

2024-11-05 12:09 UTC, ZuzaOsa commented on lib/types/result-set.js
> +    this.rows = getRowsFromResultsWrapper(result);
ResultSet should be changed to classes syntax from prototypes.

2024-11-05 15:26 UTC, adespawn commented on test/unit/cql-value-wrapper.js
> +        assert.strictEqual(value, "test value");
> This is error-prone
Yes, but those errors should be quickly catched be the tests
> quite a lot of labour
unforunetly I don't see other easy way of testing it.

2024-11-05 15:42 UTC, ZuzaOsa commented on test/unit/cql-value-wrapper.js
> +        // TODO
Unwanted TODO? Or missing description what should be done?

2024-11-05 15:42 UTC, ZuzaOsa commented on lib/types/results-wrapper.js
> + * @param {rust.CqlValueWrapper} field
This was not fixed.

2024-11-06 09:30 UTC, ZuzaOsa approved these changes

2024-11-06 09:31 UTC, ZuzaOsa reviewed
Remember to run cargo fmt

2024-11-06 09:36 UTC, wprzytula approved these changes

2024-11-06 09:56 UTC, merged